### ISSUE TITLE
Licence missing

### ISSUE THREAD

**Issue by amarao** [Roadmaster/forcediphttpsadapter#6]
Sorry for bothering you with such mundane things.

I found your code is really helping in tests (bypassing CloudFlare and having a direct request to the server), but I can't use it, because there is no license available (therefore, any use of it would be a copyright violation).

Can you, please, license it as MIT?

**Comment by Roadmaster** [comment]
Done.

(It's simple enough that I don't mind the MIT license - I would prefer LGPLv3 otherwise).

**Comment by amarao** [comment]
Thank you very much! I appreciate your help!
